### ISSUE TITLE
오류 찾아보기 && norm 정리

### ISSUE THREAD

**Issue by hwsonnn** [ShipShell/minishell#67]

**Comment by hwsonnn** [comment]
redir 오류 모두 해결!
시방서 오류
1. echo -nnnn / echo -n -n -n
2. echo $? 제대로 출력 안됨

**Comment by hwsonnn** [comment]
실행부 norm 정리 한번 함

**Comment by Likilee** [comment]
굿잡이요!!!!! 내일 같이 호로딱 이슈 체킹해봅시당
